#include <iostream>
#include <cmath>
#include <functional>
#include <GaussQuad/All>
#include <Interpolation/All>
#include <filesystem>
#include <fstream>
#include <Eigen/Core>
#include <PlanetaryModel/All>
#include <Eigen/Eigenvalues>
#include <Spectra/MatOp/SparseGenMatProd.h>
#include <Spectra/SymGEigsSolver.h>
#include <PlanetaryModel/All>
#include <Spectra/SymGEigsShiftSolver.h>
#include "toroidal.h"
#include "toroidal_clean.h"
#include "toroidal_bench.h"
