#include <iostream>
#include <cmath>
#include <functional>
#include <filesystem>
#include <fstream>
#include <Eigen/SparseCore>
#include <Eigen/SparseLU>
#include <PlanetaryModel/All>
#include "SourceInfo.h"
#include "MatrixIndices.h"
#include "toroidal_bench.h"